#Please no delete or change name variables
#|---------------------------------------|
#|         DISCORD LINK PLUGIN           |
#| Author: MiiTnT       Contributors:    |
#|---------------------------------------|
#But you can manually change values

DiscordLink: "https://discord.gg/mc-fr"
